const config = {
    style: 'mapbox://styles/jgreen1/ckngacue3009o18k943qv0fth',
    accessToken: 'pk.eyJ1IjoiamdyZWVuMSIsImEiOiJja2xhMHEwbDMydHFqMzB0N3FxdTAyYjl6In0.Hv__9wnsQJpvHjh-zLgZMw',
    showMarkers: true,
    markerColor: '#3FB1CE',
    theme: 'light',
    use3dTerrain: true,
    title: '2020 Canadian Pipeline and Railway Protests Timeline',
    subtitle: 'The Ongoing Struggle for Reconciliation and Respect of Indigenous Rights',
    byline: 'By Joshua Green',
    footer: ' ',
    chapters: [{
        id: 'chapter_00',
        alignment: 'left',
        hidden: false,
        title: 'This is an interactive scrolleytelling map. Scroll down to move to the story forward.',
        image: '',
        description: '',
        location: {
            center: { lon: -123.13579, lat: 55.15443 },
	    zoom: 4.74,
	    pitch: 44.00,
	    bearing: 0.00,
        },
        mapAnimation: 'flyTo',
        rotateAnimation: false,
        callback: '',
        onChapterEnter: [],
        onChapterExit: [],
    },{
        id: 'chapter_01',
        alignment: 'left',
        hidden: false,
        title: 'Dec 31 (2020) - Jan 1 (2021): Coastal GasLink Injunction',
        image: '',
        description: 'Dec 31 - In response to ongoing obstruction of the Coastal GasLink Project by members of the Wet’suwet’en First Nation, the B.C. Supreme Court issue an injunction ordering protestors to stop. It calls for the removal of any obstructions including cabins and gates on any roads, bridges or work sites the company has been authorized to use. Shortly after the injunction is issue the RCMP arrest 14 protesters.\
	Jan 1 - The following day the Wet’ suwet’ en First Nation herediatary chiefs serve Coastal GasLink with an eviction notice,	rejecting the injunction.They order the RCMP and Coastal GasLink personnel from the Wetʼsuwetʼen territory, stating that company workers are trespassing on their unceded territory.',
        location: {
            center: [-127.36335, 54.19083],
            zoom: 8,
            pitch: 43.50,
            bearing: 157.56,
        },
        mapAnimation: 'flyTo',
        rotateAnimation: false,
        callback: '',
        onChapterEnter: [],
        onChapterExit: [],
    }, {
        id: 'chapter_02',
        alignment: 'left',
        hidden: false,
        title: 'Jan 7 - 16: Calls to Halt Coastal GasLink by Humanitarian Rights Groups',
        image: '',
        description: "Jan 7 - The UN Committee on the Elimination of Racial Discrimination calls on Canada to immediately stop the construction of the Coastal GasLink (CGL) and Trans Mountain pipelines and the Site C dam.\
	Jan 11 - BC Human Rights Commissioner Kasari Govender calls for a halt to the CGL pipeline until the affected Indigenous groups consent to the construction\
	Jan 16 - UN committee chair Noureddine Amir admits to media that he was unaware that the CGL had broad Indigenous backing other than the Wet 'suwet'en	Jan 16 - Karen Ogen - Toews,\
	chair of the First Nations LNG Alliance and former Wetʼsuwetʼen elected chief, writes an open letter to the UN asking for a retraction and immediate apology to the 20 First Nations who are in favour of the project",
        location: {
            center: [-123.38389, 53.64046],
            zoom: 5.35,
            pitch: 35.00,
            bearing: 0.59,
        },
        mapAnimation: 'flyTo',
        rotateAnimation: false,
        callback: '',
        onChapterEnter: [],
        onChapterExit: [],
    }, {
        id: 'chapter_03',
        alignment: 'left',
        hidden: false,
        title: 'Jan 20: Marine Port Protest',
        image: '',
        description: "Jan 20 - Protesters disrupt BC ferry service leaving from Swartz Bay ferry terminal, which is Victoria's main ferry link to the BC mainland.",
        location: {
            center: [-123.41039, 48.68795],
            zoom: 13.83,
            pitch: 46.50,
            bearing: 0.00,
        },
        mapAnimation: 'flyTo',
        rotateAnimation: false,
        callback: '',
        onChapterEnter: [],
        onChapterExit: [],
    }, {
        id: 'chapter_04',
        alignment: 'left',
        hidden: false,
        title: 'Jan 21: Government Building Protest',
        image: '',
        description: 'Jan 21 - Protesters occupy the Ministry of Energy, Mines and Petroleum Resources building in Victoria for 15 hours. While using minimum force to remove the protesters, police say they were subject to physical abuse and race-based insults.',
        location: {
            center: [-123.36219, 48.43019],
            zoom: 13.93,
            pitch: 28.50,
            bearing: 7.31,
        },
        mapAnimation: 'flyTo',
        rotateAnimation: false,
        callback: '',
        onChapterEnter: [],
        onChapterExit: [],
    }, {
        id: 'chapter_05',
        alignment: 'left',
        hidden: false,
        title: 'Jan 30 - Feb 4: Wet’suwet’en Hereditary Chief and BC Government Negotiation Attempts',
        image: '',
        description: "Jan 30 - The RCMP announce that they will stand down while the hereditary chiefs and the province meet to discuss and try to come to an agreement. The hereditary chiefs of the Wet’suwet’en then agree to a seven day meetings with the B.C. government.\
	Feb 1 - The next day the Office of the Hereditary Chiefs of the Wetʼsuwetʼen again give an 'eviction notice' to the Coastal GasLink Pipeline construction camp.\
	Feb 3 - The Office of the Wetʼsuwetʼen further seek a judicial review of the environmental approval	for the pipeline.\
	Feb 3 - In Hamilton Ontario, approximately 50 protesters block the CN tracks crossing Victoria Avenue North at Birge Street in solidarity with the Wet 'suwet'en nation.\
	Feb 4– After only two days negotiations between the Wetʼsuwetʼen Hereditary Chiefs and the Government of British Columbia\
	break down.\
	Feb 6 - Shortly after the talks fail, RCMP move in to Wet’ suwet’ en territory to enforce the court injunction allowing construction work to resume. Between February 6 and 9, the RCMP arrest 21 people at camps.",
        location: {
            center: [-123.38389, 53.64046],
            zoom: 5.35,
            pitch: 35.00,
            bearing: 0.59,
        },
        mapAnimation: 'flyTo',
        rotateAnimation: false,
        callback: '',
        onChapterEnter: [],
        onChapterExit: [],
    }, {
        id: 'chapter_06',
        alignment: 'left',
        hidden: false,
        title: 'Feb 6: Wet’suwet’en Hereditary Chief and BC Government Negotiations Fail',
        image: '',
        description: 'Feb 6 - Shortly after the talks fail, RCMP move in to Wet’suwet’en territory to enforce the court injunction allowing construction work to resume. Between February 6 and 9, the RCMP arrest 21 people at camps.',
        location: {
            center: [-123.38389, 53.64046],
            zoom: 5.35,
            pitch: 35.00,
            bearing: 0.59,
        },
        mapAnimation: 'flyTo',
        rotateAnimation: false,
        callback: '',
        onChapterEnter: [],
        onChapterExit: [],
    }, {
        id: 'chapter_07',
        alignment: 'left',
        hidden: false,
        title: ': Onset of National Protest',
        image: '',
        description: 'Actions by RCMP and the British Columbia Government and the situation as a whole spark national outrage, driving dialogue on issues of Indigenous Rights and Oil & Gas in a time of climate change. In the weeks to come, protests in solidarity with the Wetʼsuwetʼen First Nation spring up all throughout Canada and gaining global attention.',
        location: {
            center: [-94.93017, 57.67839],
            zoom: 3.48,
            pitch: 35.00,
            bearing: 0.59,
        },
        mapAnimation: 'flyTo',
        rotateAnimation: false,
        callback: '',
        onChapterEnter: [],
        onChapterExit: [],
    }, {
        id: 'chapter_08',
        alignment: 'left',
        hidden: false,
        title: 'Feb 6: Railway Protest',
        image: '',
        description: 'Feb 6 – Near Belleville, Ontario, members of the Mohawks of the Bay of Quinte First Nation begin a blockade of the Canadian National Railway rail line just north of Tyendinaga Mohawk Territory. The line is critical to the CNR network in Eastern Canada as CNR has no other east–west rail lines through Eastern Ontario. Hours later, outside of Belleville, Ont., east of Toronto, protesters start holding up railway traffic in solidarity with the Wet’suwet’en hereditary chiefs. In Ontario, a blockade is erected in Tyendinaga preventing CN Rail traffic. Via Rail cancels trains on their Toronto–Montreal and Toronto-Ottawa routes. Until February 13, Via Rail announces passenger train cancellations on a day-to-day basis. Via Rail halts service along one of its busiest routes because of the Belleville-area blockade. All travel between Toronto, Ottawa and Montreal is cancelled. Canadian National Railway obtains a court injunction to end a demonstration by members of the Tyendinaga Mohawk Territory near Belleville. CN Rail’s court injunction is not enforced in Ontario, prompting the rail service to shut down all operations in Eastern Canada.',
        location: {
            center: {
                lon: -77.24409,
                lat: 44.22166,
            },
            zoom: 10.44,
            pitch: 25.50,
            bearing: 0.79,
        },
        mapAnimation: 'flyTo',
        rotateAnimation: false,
        callback: '',
        onChapterEnter: [],
        onChapterExit: [],
    }, {
        id: 'chapter_09',
        alignment: 'left',
        hidden: false,
        title: 'Feb 7: Marine Port Protest',
        image: '',
        description: 'Protesters begin disruptions at ports in Vancouver and Delta, B.C.',
        location: {
            center: {
                lon: -123.15154,
                lat: 49.21244,
            },
            zoom: 8.61,
            pitch: 0.00,
            bearing: 0.00,
        },
        mapAnimation: 'flyTo',
        rotateAnimation: false,
        callback: '',
        onChapterEnter: [],
        onChapterExit: [],
    }, {
        id: 'chapter_10',
        alignment: 'left',
        hidden: false,
        title: 'Feb 7: Street Protest',
        image: '',
        description: 'Feb. 7 In Kamloops BC, protesters occupy the busy Summit Drive and McGill Road intersection.',
        location: {
            center: {
                lon: -120.35783,
                lat: 50.66912,
            },
            zoom: 13.69,
            pitch: 25.00,
            bearing: 0.00,
        },
        mapAnimation: 'flyTo',
        rotateAnimation: false,
        callback: '',
        onChapterEnter: [],
        onChapterExit: [],
    }, {
        id: 'chapter_11',
        alignment: 'left',
        hidden: false,
        title: 'Feb 7: Highway Protest',
        image: '',
        description: 'Feb. 7 protesters slowed down and stalled traffic on Highway 10 near Balcarres, Sask. Protesters accused the RCMP of being bought off by corporations.',
        location: {
            center: {
                lon: -103.54011,
                lat: 50.79834,
            },
            zoom: 14.85,
            pitch: 50.50,
            bearing: 0.00,
        },
        mapAnimation: 'flyTo',
        rotateAnimation: false,
        callback: '',
        onChapterEnter: [],
        onChapterExit: [],
    }, {
        id: 'chapter_12',
        alignment: 'left',
        hidden: false,
        title: 'Feb 7: Bridge Protest',
        image: '',
        description: 'Feb. 7 protesters shut down the Seaway International Bridge in Cornwall, Ont.',
        location: {
            center: {
                lon: -74.73869,
                lat: 44.98945,
            },
            zoom: 10.99,
            pitch: 28.50,
            bearing: 9.99,
        },
        mapAnimation: 'flyTo',
        rotateAnimation: false,
        callback: '',
        onChapterEnter: [],
        onChapterExit: [],
    }, {
        id: 'chapter_13',
        alignment: 'left',
        hidden: false,
        title: 'Feb 8: Railway Protest',
        image: '',
        description: 'Protesters in Toronto disrupt Canadian Pacific Railway traffic moving through the downtown area.',
        location: {
            center: {
                lon: -79.39862,
                lat: 43.65560,
            },
            zoom: 11.44,
            pitch: 15.00,
            bearing: 0.00,
        },
        mapAnimation: 'flyTo',
        rotateAnimation: false,
        callback: '',
        onChapterEnter: [],
        onChapterExit: [],
    }, {
        id: 'chapter_14',
        alignment: 'left',
        hidden: false,
        title: 'Feb 8: Railway Protest',
        image: '',
        description: "February 8 - A blockade of the Exo's Candiac line south of Montreal in Kahnawake begins. Kahnawake Mohawk community members south of Montreal erect a blockade on a CP rail line.",
        location: {
            center: {
                lon: -73.65039,
                lat: 45.40501,
            },
            zoom: 12.02,
            pitch: 33.00,
            bearing: 5.98,
        },
        mapAnimation: 'flyTo',
        rotateAnimation: false,
        callback: '',
        onChapterEnter: [],
        onChapterExit: [],
    }, {
        id: 'chapter_15',
        alignment: 'left',
        hidden: false,
        title: 'Feb 8: Marine Port Protest',
        image: '',
        description: 'Feb. 8 protesters occupied the Deltaport in Delta, B.C. On Feb. 10 RCMP broke up the blockade, arresting 14.',
        location: {
            center: {
                lon: -123.15848,
                lat: 49.02100,
            },
            zoom: 9.96,
            pitch: 0.00,
            bearing: 0.00,
        },
        mapAnimation: 'flyTo',
        rotateAnimation: false,
        callback: '',
        onChapterEnter: [],
        onChapterExit: [],
    }, {
        id: 'chapter_16',
        alignment: 'left',
        hidden: false,
        title: 'Feb 8: Railway Protest',
        image: '',
        description: 'Feb. 8, protesters set up a blockade on the rail tracks near New Hazelton, B.C., cutting off rail access to Prince Rupert and Kitimat. On Feb. 13 protesters dismantled the blockade as they negotiate with RCMP. Protesters say that unless Coastal GasLink is cancelled they will resume the blockade in the future',
        location: {
            center: {
                lon: -127.58082,
                lat: 55.24956,
            },
            zoom: 11.66,
            pitch: 15.00,
            bearing: 0.00,
        },
        mapAnimation: 'flyTo',
        rotateAnimation: false,
        callback: '',
        onChapterEnter: [],
        onChapterExit: [],
    }, {
        id: 'chapter_17',
        alignment: 'left',
        hidden: false,
        title: 'Feb 9: Railway Protest',
        image: '',
        description: 'Feb. 9 protesters blockaded rail tracks near Belleville, Ont. The RCMP in Ontario has secured a court-ordered injunction to clear the blockade, but so far no action has been taken to remove the protesters.',
        location: {
            center: {
                lon: -77.24409,
                lat: 44.22166,
            },
            zoom: 10.44,
            pitch: 25.50,
            bearing: 0.79,
        },
        mapAnimation: 'flyTo',
        rotateAnimation: false,
        callback: '',
        onChapterEnter: [],
        onChapterExit: [],
    }, {
        id: 'chapter_18',
        alignment: 'left',
        hidden: false,
        title: 'Feb 10: Bank Protest',
        image: '',
        description: 'Feb. 10 protesters occupied the Bank of Montreal branch in Nelson, B.C. for several days because bank had given a loan to TransCanada to build the Coastal GasLink pipeline. Police said they would not be removing the protesters, leading to the protest lasting several days before they all left.',
        location: {
            center: {
                lon: -117.29652,
                lat: 49.49065,
            },
            zoom: 13.54,
            pitch: 31.00,
            bearing: 0.00,
        },
        mapAnimation: 'flyTo',
        rotateAnimation: false,
        callback: '',
        onChapterEnter: [],
        onChapterExit: [],
    }, {
        id: 'chapter_19',
        alignment: 'left',
        hidden: false,
        title: 'Feb 10: Railway Protest',
        image: '',
        description: 'Demonstrators in the Montreal area disrupt commuter train service on the Exo Candiac line. A shuttle bus service is in effect for affected rail stations.',
        location: {
            center: {
                lon: -73.55543,
                lat: 45.51086,
            },
            zoom: 10.15,
            pitch: 27.00,
            bearing: 0.00,
        },
        mapAnimation: 'flyTo',
        rotateAnimation: false,
        callback: '',
        onChapterEnter: [],
        onChapterExit: [],
    }, {
        id: 'chapter_20',
        alignment: 'left',
        hidden: false,
        title: 'Feb 10: Marine Port Protest',
        image: '',
        description: "February 10 – protesters set up blockades at the three entrences to the Port of Vancouver, Canada's largest port. The protest began at 5:30 a.m. By 8:00 a.m. police broke up blockade at the Hastings and Clark entrance. Metro Vancouver police arrest 47 persons blocking the Port of Vancouver, Delta port, and two other ports in Metro Vancouver.",
        location: {
            center: {
                lon: -123.08170,
                lat: 49.31430,
            },
            zoom: 11.59,
            pitch: 53.00,
            bearing: -35.20,
        },
        mapAnimation: 'flyTo',
        rotateAnimation: false,
        callback: '',
        onChapterEnter: [],
        onChapterExit: [],
    }, {
        id: 'chapter_21',
        alignment: 'left',
        hidden: false,
        title: 'Feb 10: Railway Protest',
        image: '',
        description: 'February 10 – A blockade goes up on the CNR line west of Winnipeg blocking the trans-Canada passenger rail route.',
        location: {
            center: {
                lon: -97.13960,
                lat: 49.89498,
            },
            zoom: 11.79,
            pitch: 25.00,
            bearing: 3.32,
        },
        mapAnimation: 'flyTo',
        rotateAnimation: false,
        callback: '',
        onChapterEnter: [],
        onChapterExit: [],
    }, {
        id: 'chapter_22',
        alignment: 'left',
        hidden: false,
        title: 'Feb 10: Railway Protest',
        image: '',
        description: 'February 10 – The Société de chemin de fer de la Gaspésie (SCFG) freight railway between Gaspé and Matapédia, Quebec is blockaded by members of the Listuguj Miꞌgmaq First Nation.',
        location: {
            center: {
                lon: -65.82956,
                lat: 48.16236,
            },
            zoom: 12.26,
            pitch: 42.50,
            bearing: 2.37,
        },
        mapAnimation: 'flyTo',
        rotateAnimation: false,
        callback: '',
        onChapterEnter: [],
        onChapterExit: [],
    }, {
        id: 'chapter_23',
        alignment: 'left',
        hidden: false,
        title: 'Feb 10: Railway Protest',
        image: '',
        description: 'Feb.10 After a week of demonstrations, protesters in Kahnawake, Que. began a permanent blockade of rail lines.',
        location: {
            center: {
                lon: -73.66234,
                lat: 45.41005,
            },
            zoom: 13.45,
            pitch: 24.00,
            bearing: 14.79,
        },
        mapAnimation: 'flyTo',
        rotateAnimation: false,
        callback: '',
        onChapterEnter: [],
        onChapterExit: [],
    }, {
        id: 'chapter_24',
        alignment: 'left',
        hidden: false,
        title: 'Feb 10: Bridge Protest',
        image: '',
        description: 'Feb. 10 protesters blocked the Reconciliation Bridge in Calgary.',
        location: {
            center: {
                lon: -114.05208,
                lat: 51.05042,
            },
            zoom: 13.98,
            pitch: 32.50,
            bearing: 0.00,
        },
        mapAnimation: 'flyTo',
        rotateAnimation: false,
        callback: '',
        onChapterEnter: [],
        onChapterExit: [],
    }, {
        id: 'chapter_25',
        alignment: 'left',
        hidden: false,
        title: 'Feb 11: Railway Protest',
        image: '',
        description: 'February 11 – Prince George–Prince Rupert passenger rail service is suspended. CN stops transport between Prince George, B.C., and Prince Rupert, B.C., because of a blockade near Hazelton, B.C. The company says it has halted more than 150 freight trains since blockades started on Feb. 6.',
        location: {
            center: {
                lon: -130.26805,
                lat: 54.24239,
            },
            zoom: 6.22,
            pitch: 32.50,
            bearing: -0.43,
        },
        mapAnimation: 'flyTo',
        rotateAnimation: false,
        callback: '',
        onChapterEnter: [],
        onChapterExit: [],
    }, {
        id: 'chapter_26',
        alignment: 'left',
        hidden: false,
        title: 'Feb 11: Government Building Protest',
        image: '',
        description: 'February 11 – protesters demonstrating outside the Legislative Assembly of British Columbia block the entrances A solidarity rally surrounds the BC Legislature in Victoria, preventing the spring sitting and traditional ceremonies around the reading of the Throne Speech by the Lieutenant Governor. Members of the Legislature have police assistance to enter or use back or side entrances. Victoria police are investigating allegations of protesters assaulting government staff.',
        location: {
            center: [-123.37001, 48.42015],
            zoom: 16.44,
            pitch: 46.00,
            bearing: -165.20,
        },
        mapAnimation: 'flyTo',
        rotateAnimation: false,
        callback: '',
        onChapterEnter: [],
        onChapterExit: [],
    }, {
        id: 'chapter_27',
        alignment: 'left',
        hidden: false,
        title: 'Feb 11: Highway Protest',
        image: '',
        description: 'Feb. 11 protesters set up a blockade on Highway 19 near Courtenay, B.C. Police later arrested a local resident who tried to take down the barricade, rather than the protesters themselves. RCMP would later take down the blockade that day.',
        location: {
            center: {
                lon: -125.00913,
                lat: 49.63307,
            },
            zoom: 10.83,
            pitch: 25.00,
            bearing: -1.45,
        },
        mapAnimation: 'flyTo',
        rotateAnimation: false,
        callback: '',
        onChapterEnter: [],
        onChapterExit: [],
    }, {
        id: 'chapter_28',
        alignment: 'left',
        hidden: false,
        title: 'Feb 11: Street Protest',
        image: '',
        description: 'Feb. 11 protesters shut down the intersection of Yonge and Eglinton streets, causing major traffic disruptions in the area.',
        location: {
            center: {
                lon: -79.39832,
                lat: 43.70675,
            },
            zoom: 16.04,
            pitch: 31.00,
            bearing: 0.00,
        },
        mapAnimation: 'flyTo',
        rotateAnimation: false,
        callback: '',
        onChapterEnter: [],
        onChapterExit: [],
    }, {
        id: 'chapter_29',
        alignment: 'left',
        hidden: false,
        title: 'Feb 12: Railway Protest',
        image: '',
        description: 'Feb. 12, protesters blockaded the rails near Headingly, Mb. The Manitoba government says it may seek a court injunction to end a blockade on a rail line west of Winnipeg, but CN obtains its own court order. Less than 24 hours later the blockade was taken down by RCMP. Premier Brian Pallister later said he would not stand for illegal blockades in his province.',
        location: {
            center: {
                lon: -97.40570,
                lat: 49.87616,
            },
            zoom: 10.09,
            pitch: 19.50,
            bearing: 0.00,
        },
        mapAnimation: 'flyTo',
        rotateAnimation: false,
        callback: '',
        onChapterEnter: [],
        onChapterExit: [],
    }, {
        id: 'chapter_30',
        alignment: 'left',
        hidden: false,
        title: 'Feb 12: Bridge Protest',
        image: '',
        description: 'Feb. 12 a group of protesters blocked the Granville Bridge in both directions. The protest lasted throughout the afternoon. The same day protesters blocked the intersection at Cambie and Broadway.',
        location: {
            center: {
                lon: -123.13310,
                lat: 49.27272,
            },
            zoom: 13.06,
            pitch: 29.50,
            bearing: 0.00,
        },
        mapAnimation: 'flyTo',
        rotateAnimation: false,
        callback: '',
        onChapterEnter: [],
        onChapterExit: [],
    }, {
        id: 'chapter_31',
        alignment: 'left',
        hidden: false,
        title: 'Feb 13: Railway Protest',
        image: '',
        description: 'February 13 – Via Rail announces the shutdown of its entire network, with the exception of the Sudbury–White River train line and the Winnipeg–Churchill train between Churchill and The Pas, until further notice. CN shuts down its operations in Eastern Canada. The railway says blockades have ended in Manitoba and may come down soon in British Columbia, but the orders of a court in Ontario have yet to be enforced and continue to be ignored. CN Rail’s court injunction is not enforced in Ontario, prompting the rail service to shut down all operations in Eastern Canada. CN Rail says blockades in Manitoba end and expect those in B.C. to follow suit. CNR shuts down its rail lines east of Toronto',
        location: {
            center: {
                lon: -127.17357,
                lat: 54.78147,
            },
            zoom: 13.01,
            pitch: 15.00,
            bearing: 0.00,
        },
        mapAnimation: 'flyTo',
        rotateAnimation: false,
        callback: '',
        onChapterEnter: [],
        onChapterExit: [],
    }, {
        id: 'chapter_32',
        alignment: 'left',
        hidden: false,
        title: 'Feb 14: Street Protest',
        image: '',
        description: 'Feb. 14 protesters shut down the intersection of Yonge and Dundas streets, causing major traffic disruptions in the area',
        location: {
            center: {
                lon: -79.38101,
                lat: 43.65644,
            },
            zoom: 13.97,
            pitch: 30.00,
            bearing: 0.41,
        },
        mapAnimation: 'flyTo',
        rotateAnimation: false,
        callback: '',
        onChapterEnter: [],
        onChapterExit: [],
    }, {
        id: 'chapter_33',
        alignment: 'left',
        hidden: false,
        title: 'Feb 14: Railway Protest',
        image: '',
        description: 'Feb. 14 protesters began occupying the CP Rail yard in Coquitlam, B.C., blocking rail access to the Port of Vancouver. The group occupying the rail yard says they will remain until the Coastal GasLink pipeline is cancelled or they are forced out.',
        location: {
            center: {
                lon: -122.76612,
                lat: 49.26129,
            },
            zoom: 11.20,
            pitch: 38.50,
            bearing: 0.00,
        },
        mapAnimation: 'flyTo',
        rotateAnimation: false,
        callback: '',
        onChapterEnter: [],
        onChapterExit: [],
    }, {
        id: 'chapter_34',
        alignment: 'left',
        hidden: false,
        title: 'Feb 15: Railway Protest',
        image: '',
        description: 'Feb. 15 Over 200 people block Macmillan Yard in Vaughn Ont, the second largest railyard in Canada. That day the protesters were served an injunction, which they promptly burnt.',
        location: {
            center: {
                lon: -79.51232,
                lat: 43.81564,
            },
            zoom: 11.97,
            pitch: 33.00,
            bearing: -8.93,
        },
        mapAnimation: 'flyTo',
        rotateAnimation: false,
        callback: '',
        onChapterEnter: [],
        onChapterExit: [],
    }, {
        id: 'chapter_35',
        alignment: 'left',
        hidden: false,
        title: 'Feb 15: Railway Protest',
        image: '',
        description: "February 15 – Indigenous Services Minister Marc Miller meets the Mohawks in a ceremonial encounter on the CNR train tracks to renew a 17th Century treaty between the Iroquois and the British Crown known as the Silver Covenant Chain. Miller and the leaders of Tyendinaga then discussed the blockade Miller asked for a temporary drawback of the protest but his request was refused after Wetʼsuwetʼen hereditary Chief Woos, who was on the phone, stated that the RCMP was still on his territory and 'they are out there with guns, threatening us'. Leaked audio of the meetings included a Mohawk resident in the meeting telling the minister to 'Get the red coats out first, get the blue coats out… then we can maybe have some common discussions '. Federal Indigenous Services Minister Marc Miller travels to meet with protesters in Tyendinaga Mohawk Territory near the site of the Belleville blockade. He says “modest progress” was made during nine hours of talks, but declines to share details on what was discussed.",
        location: {
            center: {
                lon: -77.24409,
                lat: 44.22166,
            },
            zoom: 10.44,
            pitch: 25.50,
            bearing: 0.79,
        },
        mapAnimation: 'flyTo',
        rotateAnimation: false,
        callback: '',
        onChapterEnter: [],
        onChapterExit: [],
    }, {
        id: 'chapter_36',
        alignment: 'left',
        hidden: false,
        title: 'Feb 16: Bridge Protest',
        image: '',
        description: 'Feb. 16 protesters blocked the Canadian side of the Rainbow International Bridge, disrupting traffic for most of the afternoon. A demonstration temporarily blocks the Rainbow Bridge border crossing in Niagara Falls, Ontario. Meanwhile, protesters briefly shut down a busy Ontario border crossing. A protest in Ontario shuts down a U.S. border crossing.',
        location: {
            center: {
                lon: -79.06802,
                lat: 43.09097,
            },
            zoom: 12.65,
            pitch: 38.50,
            bearing: -1.78,
        },
        mapAnimation: 'flyTo',
        rotateAnimation: false,
        callback: '',
        onChapterEnter: [],
        onChapterExit: [],
    }, {
        id: 'chapter_37',
        alignment: 'left',
        hidden: false,
        title: 'Feb 17: Bridge Protest',
        image: '',
        description: 'Feb. 17 A demonstration temporarily blocks the Thousand Islands Bridge border crossing in Ivy Lea Ontario, preventing drivers from both Canada and the United States from crossing.',
        location: {
            enter: {
                lon: -75.98121,
                lat: 44.36540,
            },
            zoom: 12.97,
            pitch: 43.50,
            bearing: 12.00,
        },
        mapAnimation: 'flyTo',
        rotateAnimation: false,
        callback: '',
        onChapterEnter: [],
        onChapterExit: [],
    }, {
        id: 'chapter_38',
        alignment: 'left',
        hidden: false,
        title: 'Feb 19: Railway Protest',
        image: '',
        description: 'Feb. 19 protesters set up a blockade on the western side of Edmonton. Within the first day 30 trains had been blocked and $135 million worth of freight was affected. Counter-protesters have since dismantled the blockade. Protesters erect a blockade along a stretch of CN rail line in Edmonton, but are soon faced with counter-protesters who begin forcibly dismantling the barricade. The blockade is taken down later in the day. A group of about 20 members erects a blockade on a CN rail line in west Edmonton. CN obtains a court injunction, and less than twelve hours after the blockade began, it was dismantled by counter-protesters after a CN legal representative arrived to serve the injunction.',
        location: {
            center: {
                lon: -113.67150,
                lat: 53.56264,
            },
            zoom: 11.22,
            pitch: 22.00,
            bearing: 0.00,
        },
        mapAnimation: 'flyTo',
        rotateAnimation: false,
        callback: '',
        onChapterEnter: [],
        onChapterExit: [],
    }, {
        id: 'chapter_39',
        alignment: 'left',
        hidden: false,
        title: 'Feb 19: Railway Protest',
        image: '',
        description: 'February 19 – A blockade is set up on the Mont-Saint-Hilaire rail line in Saint-Lambert, Quebec, promising to stay until the RCMP leaves the disputed zone in Wetʼsuwetʼen territory. The blockade caused Via Rail to postpone resuming service between Montreal and Quebec City.',
        location: {
            center: {
                lon: -73.18183,
                lat: 45.57142,
            },
            zoom: 10.97,
            pitch: 19.50,
            bearing: 0.38,
        },
        mapAnimation: 'flyTo',
        rotateAnimation: false,
        callback: '',
        onChapterEnter: [],
        onChapterExit: [],
    }, {
        id: 'chapter_40',
        alignment: 'left',
        hidden: false,
        title: 'Feb 20 - 21: Railway Protest',
        image: '',
        description: 'Feb. 20 Another blockade of CPR tracks springs up in Neskonlith, BC between Kamloops and Chase.\
	Feb.21 Protesters in Neskonlith BC leave voluntarily after the RCMP leave Wet’ suwet’ en land.They vow to return infour daysif a dialogue was not started between the prime minister and the hereditary chiefs.',
        location: {
            center: {
                lon: -119.72221,
                lat: 50.77362,
            },
            zoom: 12.22,
            pitch: 51.50,
            bearing: 0.00,
        },
        mapAnimation: 'flyTo',
        rotateAnimation: false,
        callback: '',
        onChapterEnter: [],
        onChapterExit: [],
    }, {
        id: 'chapter_41',
        alignment: 'left',
        hidden: false,
        title: 'Feb 20: RCMP Move off Wet’suwet’en Territory',
        image: '',
        description: "- Federal Public Safety Minister Bill Blair says the RCMP has offered to move its officers from Wet’suwet’en territory to a nearby town. He says this concession meets a key condition from the hereditary chiefs and calls for all rail blockades to be dismantled.\
	- The Civilian Review and Complaints Commission(CRCC) for the RCMP issues a letter critical of RCMP procedures in the checkpoint and exclusion zone implemented on the Morice West Forest Service Road, stating the RCMP went beyond its legal authority to do ID checks of activists and searches of activists' vehicles.\
	- The RCMP then offer to close its Community Industry Security Office (CISO) on the Morice Road.\
	- The RCMP moves off of Wet’ suwet’ en territory into a nearby town, which Federal Public Safety Minister Bill Blair says meets a key condition from the hereditary chiefs.",
        location: {
            center: [-123.38389, 53.64046],
            zoom: 5.35,
            pitch: 35.00,
            bearing: 0.59,
        },
        mapAnimation: 'flyTo',
        rotateAnimation: false,
        callback: '',
        onChapterEnter: [],
        onChapterExit: [],
    }, {
        id: 'chapter_42',
        alignment: 'left',
        hidden: false,
        title: 'Feb 21: Railway Protest',
        image: '',
        description: 'February 21 – The Mont-Saint-Hilaire rail line is cleared after the Sûreté du Québec police arrive to enforce a CNR injunction.',
        location: {
            center: {
                lon: -73.18183,
                lat: 45.57142,
            },
            zoom: 10.97,
            pitch: 19.50,
            bearing: 0.38,
        },
        mapAnimation: 'flyTo',
        rotateAnimation: false,
        callback: '',
        onChapterEnter: [],
        onChapterExit: [],
    }, {
        id: 'chapter_43',
        alignment: 'left',
        hidden: false,
        title: 'Feb 21: Railway Protest',
        image: '',
        description: 'February 21 – Wetʼsuwetʼen supporters block CNR rail lines near Moncton, New Brunswick.',
        location: {
            center: {
                lon: -64.78176,
                lat: 46.08782,
            },
            zoom: 13.33,
            pitch: 34.50,
            bearing: -16.20,
        },
        mapAnimation: 'flyTo',
        rotateAnimation: false,
        callback: '',
        onChapterEnter: [],
        onChapterExit: [],
    }, {
        id: 'chapter_44',
        alignment: 'left',
        hidden: false,
        title: 'Feb 22: Street Protest',
        image: '',
        description: 'Thousands of protesters rally in downtown Toronto in support of the Wet’suwet’en hereditary chiefs who are opposed to Coast GasLink pipeline.',
        location: {
            center: {
                lon: -79.38686,
                lat: 43.64337,
            },
            zoom: 13.44,
            pitch: 27.50,
            bearing: 0.00,
        },
        mapAnimation: 'flyTo',
        rotateAnimation: false,
        callback: '',
        onChapterEnter: [],
        onChapterExit: [],
    }, {
        id: 'chapter_45',
        alignment: 'left',
        hidden: false,
        title: 'Feb 22: Railway Protest',
        image: '',
        description: 'Anti-pipeline demonstrations spring up, including a protest along the railway tracks in Saskatoon. Saskatchewan Premier Scott Moe says a train was allowed to pass through the protest area as scheduled, warning that the protest must remain lawful and that transport routes cannot be disrupted by illegal blockades.',
        location: {
            center: {
                lon: -106.68982,
                lat: 52.12925,
            },
            zoom: 11.11,
            pitch: 25.00,
            bearing: 0.00,
        },
        mapAnimation: 'flyTo',
        rotateAnimation: false,
        callback: '',
        onChapterEnter: [],
        onChapterExit: [],
    }, {
        id: 'chapter_46',
        alignment: 'left',
        hidden: false,
        title: 'Feb 23: Railway Protest',
        image: '',
        description: 'February 23 – Mohawks at the Tyendinaga rail blockade are given notice by the OPP to clear their blockade by midnight to avoid prosecution for disobeying the injunction against the blockade. Ontario Provincial Police give protesters until midnight Sunday to clear the blockade near Belleville on Tyendinaga Mohawk Territory or face an investigation and possible criminal charges.',
        location: {
            center: {
                lon: -77.24409,
                lat: 44.22166,
            },
            zoom: 10.44,
            pitch: 25.50,
            bearing: 0.79,
        },
        mapAnimation: 'flyTo',
        rotateAnimation: false,
        callback: '',
        onChapterEnter: [],
        onChapterExit: [],
    }, {
        id: 'chapter_47',
        alignment: 'left',
        hidden: false,
        title: 'Feb 24: Railway Protest',
        image: '',
        description: 'Feb. 24 Members of the Mohawk Nation (Bear Clan) from the Six Nations of the Grand River First Nation block Ontario Highway 6 in Caledonia in solidarity with the Wetʼsuwetʼen.',
        location: {
            center: {
                lon: -79.95787,
                lat: 43.07062,
            },
            zoom: 11.83,
            pitch: 32.00,
            bearing: 21.04,
        },
        mapAnimation: 'flyTo',
        rotateAnimation: false,
        callback: '',
        onChapterEnter: [],
        onChapterExit: [],
    }, {
        id: 'chapter_48',
        alignment: 'left',
        hidden: false,
        title: 'Feb 24: Railway Protest',
        image: '',
        description: "Feb. 24 protesters occupied a section of rail in Rimouski, Que. Protesters were seen holding signs with anarchist slogans and calls for police to leave Wet'suwet'en traditional territory. The protesters disturbed peacefully after police arrived to enforce an injunction.",
        location: {
            center: {
                lon: -68.52439,
                lat: 48.44815,
            },
            zoom: 13.98,
            pitch: 28.50,
            bearing: 0.46,
        },
        mapAnimation: 'flyTo',
        rotateAnimation: false,
        callback: '',
        onChapterEnter: [],
        onChapterExit: [],
    }, {
        id: 'chapter_49',
        alignment: 'left',
        hidden: false,
        title: 'Feb 24: Bridge & Railway Protest',
        image: '',
        description: "Feb. 24 Immediately following the police action, new protests spring up in the province of Quebec including a temporary rolling blockade of the Honoré Mercier Bridge near Montreal by Mohawks from Kahnawake and a barricade of Route 344 which was the site of the 1990 Oka Crisis. They also stop transport trucks from moving through Listuguj Mi'gmaq territory on their way to the Quebec-New Brunswick border. Protesters have blocked the railways near the Quebec-New Brunswick since January.",
        location: {
            center: {
                lon: -73.66090,
                lat: 45.40857,
            },
            zoom: 12.65,
            pitch: 42.50,
            bearing: 14.27,
        },
        mapAnimation: 'flyTo',
        rotateAnimation: false,
        callback: '',
        onChapterEnter: [],
        onChapterExit: [],
    }, {
        id: 'chapter_50',
        alignment: 'left',
        hidden: false,
        title: 'Feb 24: Railway Protest',
        image: '',
        description: 'February 24 – Rail blockades come down in New Brunswick after being served with an injunction.',
        location: {
            center: {
                lon: -72.09487,
                lat: 46.08674,
            },
            zoom: 6.50,
            pitch: 30.00,
            bearing: 7.07,
        },
        mapAnimation: 'flyTo',
        rotateAnimation: false,
        callback: '',
        onChapterEnter: [],
        onChapterExit: [],
    }, {
        id: 'chapter_51',
        alignment: 'left',
        hidden: false,
        title: 'Feb 24: Railway Protest',
        image: '',
        description: 'February 24 – The Tyendinaga Mohawks do not vacate the site. The OPP removes the blockade, arresting several of the protesters. Ontario Provincial Police move to enforce injunction aimed at clearing Belleville-area rail blockade. Police make several arrests and officers line up in front of the remaining protesters at the encampment.',
        location: {
            center: {
                lon: -77.24409,
                lat: 44.22166,
            },
            zoom: 10.44,
            pitch: 25.50,
            bearing: 0.79,
        },
        mapAnimation: 'flyTo',
        rotateAnimation: false,
        callback: '',
        onChapterEnter: [],
        onChapterExit: [],
    }, {
        id: 'chapter_52',
        alignment: 'left',
        hidden: false,
        title: 'Feb 24: Government Building Protest',
        image: '',
        description: 'February 24 – New protests form in British Columbia, blocking the BC Legislature, the Port of Vancouver and rail lines in Hazelton and Kamloops. In Hazleton, 14 protesters, including three Gitxsan hereditary chiefs, are arrested. They are released overnight. More than 100 protesters are occupied the steps of the B.C. legislature building in Victoria. ',
        location: {
            center: {
                lon: -130.26805,
                lat: 54.24239,
            },
            zoom: 6.22,
            pitch: 32.50,
            bearing: -0.43,
        },
        mapAnimation: 'flyTo',
        rotateAnimation: false,
        callback: '',
        onChapterEnter: [],
        onChapterExit: [],
    }, {
        id: 'chapter_53',
        alignment: 'left',
        hidden: false,
        title: 'Feb 24: Railway Protest',
        image: '',
        description: 'Feb. 24 protesters blockaded the railway un the York Blvd. bridge in Hamilton, Ont. The protest caused mass cancellation and disruptions for GO Transit users from Hamilton to Niagara.',
        location: {
            center: {
                lon: -79.88955,
                lat: 43.27826,
            },
            zoom: 13.68,
            pitch: 43.00,
            bearing: 0.00,
        },
        mapAnimation: 'flyTo',
        rotateAnimation: false,
        callback: '',
        onChapterEnter: [],
        onChapterExit: [],
    }, {
        id: 'chapter_54',
        alignment: 'left',
        hidden: false,
        title: 'Feb 25: Railway Protest',
        image: '',
        description: 'February 25 – Members of the Six Nations of the Grand River First Nation set up a rail blockade in Hamilton, causing the cancellation of train service between Aldershot and Niagara Falls stations. The GO Metrolinx agency replaced the rail service with shuttle buses.',
        location: {
            center: {
                lon: -79.95787,
                lat: 43.07062,
            },
            zoom: 11.83,
            pitch: 32.00,
            bearing: 21.04,
        },
        mapAnimation: 'flyTo',
        rotateAnimation: false,
        callback: '',
        onChapterEnter: [],
        onChapterExit: [],
    }, {
        id: 'chapter_55',
        alignment: 'left',
        hidden: false,
        title: 'Feb 25: Railway Protest',
        image: '',
        description: 'February 25 - A demonstration blocks commuter rail lines in Toronto, causing suspension of GO train service for several hours. Several protesters are arrested. Protesters occupied a piece of rail near the Kipling GO station in Etobicoke. The blockade effected service on the Milton, Lakeshore East and Lakeshore West lines.',
        location: {
            center: {
                lon: -79.56352,
                lat: 43.70626,
            },
            zoom: 16.00,
            pitch: 32.00,
            bearing: 0.00,
        },
        mapAnimation: 'flyTo',
        rotateAnimation: false,
        callback: '',
        onChapterEnter: [],
        onChapterExit: [],
    }, {
        id: 'chapter_56',
        alignment: 'left',
        hidden: false,
        title: 'Feb 26: Highway Protest',
        image: '',
        description: 'Feb. 26 protested occupied the Pat Bay Highway, cutting off traffic between Victoria and the upper Saanich Peninsula, including the BC Ferries terminal and the Victoria airport. Traffic was diverted and no ferries were cancelled that day.',
        location: {
            center: {
                lon: -123.40507,
                lat: 48.59378,
            },
            zoom: 9.91,
            pitch: 34.00,
            bearing: 0.00,
        },
        mapAnimation: 'flyTo',
        rotateAnimation: false,
        callback: '',
        onChapterEnter: [],
        onChapterExit: [],
    }, {
        id: 'chapter_57',
        alignment: 'left',
        hidden: false,
        title: 'Feb 27: Railway Protest',
        image: '',
        description: 'February 27 - A few dozen activists, protesting the pipeline and the OPP actions, block rail lines in Kingston, Ontario for several hours.',
        location: {
            center: {
                lon: -76.53695,
                lat: 44.25697,
            },
            zoom: 15.00,
            pitch: 44.50,
            bearing: 0.00,
        },
        mapAnimation: 'flyTo',
        rotateAnimation: false,
        callback: '',
        onChapterEnter: [],
        onChapterExit: [],
    }, {
        id: 'chapter_58',
        alignment: 'left',
        hidden: false,
        title: 'Feb 27 - March 2: New Negotiations with the Wetʼsuwetʼen First Nation',
        image: '',
        description: "February 27 - TC Energy agrees to pause construction and the RCMP stops patrolling the Morice Forest Service Road to address the Wetʼsuwetʼen hereditary chiefs' preconditions for talks with government ministers.\
    February 27 - Canadian Crown - Indigenous Relations and Northern Development Minister Carolyn Bennett and B.C.Indigenous Relations Minister Scott Fraser arrive in Smithers, British Columbia and begin two days of talks with the Wet’ suwet’ en hereditary chiefs.\
	February 28 - Wetʼsuwetʼen matriarchs join the meetings, demanding representation from all of the Wetʼsuwetʼen people.\
	March 1 - After extending talks to three days, an agreement on land rights is reached, in the form of a Memorandum of Understanding(MOU).It is to be presented to the Wetʼsuwetʼen Nation for ratification.\
	March 2 - RCMP patrols resume and CGL construction work resumes.",
        location: {
            center: [-123.38389, 53.64046],
            zoom: 5.35,
            pitch: 35.00,
            bearing: 0.59,
        },
        mapAnimation: 'flyTo',
        rotateAnimation: false,
        callback: '',
        onChapterEnter: [],
        onChapterExit: [],
    }, {
        id: 'chapter_59',
        alignment: 'left',
        hidden: false,
        title: 'Mar 2: Railway Protest',
        image: '',
        description: 'March 2 - A CNR rail bridge in Pointe-St-Charles, Quebec is blocked for several hours by protesters, who leave peacefully.',
        location: {
            center: {
                lon: -73.56112,
                lat: 45.48051,
            },
            zoom: 14.04,
            pitch: 49.00,
            bearing: 28.00,
        },
        mapAnimation: 'flyTo',
        rotateAnimation: false,
        callback: '',
        onChapterEnter: [],
        onChapterExit: [],
    }, {
        id: 'chapter_60',
        alignment: 'left',
        hidden: false,
        title: 'Mar 3: Railway Services Restored',
        image: '',
        description: 'March 3 - Via Rail resumes service on their Toronto–Montreal and Toronto–Ottawa lines.',
        location: {
            center: {
                lon: -75.64847,
                lat: 45.55407,
            },
            zoom: 5.49,
            pitch: 29.00,
            bearing: -31.51,
        },
        mapAnimation: 'flyTo',
        rotateAnimation: false,
        callback: '',
        onChapterEnter: [],
        onChapterExit: [],
    }, {
        id: 'chapter_61',
        alignment: 'left',
        hidden: false,
        title: 'Mar 3 - 8: Further Negotiations with the Wetʼsuwetʼen First Nation',
        image: '',
        description: "March 3 - A meeting is held at the Centennial Hall in Witset among the Laksilyu (Small Frog Clan), to discuss the tentative agreement reached between the hereditary chiefs and the representatives of the Canadian government. The meeting's attendees agree to the proposal on the spot.\
    March 8 - The Tsayu(Beaver Clan) hold a meeting at the Centennial Hall in Witset to discuss the tentative agreement reached on March 1. ",
        location: {
            center: [-123.38389, 53.64046],
            zoom: 5.35,
            pitch: 35.00,
            bearing: 0.59,
        },
        mapAnimation: 'flyTo',
        rotateAnimation: false,
        callback: '',
        onChapterEnter: [],
        onChapterExit: [],
    }, {
        id: 'chapter_62',
        alignment: 'left',
        hidden: false,
        title: 'Mar 4: Railway Services Restored',
        image: '',
        description: "March 4 - The Canadian, Via Rail's Toronto-Vancouver train, resumes partial service, as Via announces it is recalling most of the 1,000 employees	affected by temporary suspensions starting on February 19.",
        location: {
            center: {
                lon: -88.53632,
                lat: 51.64619,
            },
            zoom: 2.94,
            pitch: 27.00,
            bearing: 0.00,
        },
        mapAnimation: 'flyTo',
        rotateAnimation: false,
        callback: '',
        onChapterEnter: [],
        onChapterExit: [],
    }, {
        id: 'chapter_63',
        alignment: 'left',
        hidden: false,
        title: 'Mar 5: Railway Protests End',
        image: '',
        description: 'March 5 - The Mohawks of Kahnawake First Nation and dismantle their rail blockades in Quebec.',
        location: {
            center: {
                lon: -73.67606,
                lat: 45.40994,
            },
            zoom: 11.24,
            pitch: 46.50,
            bearing: -20.96,
        },
        mapAnimation: 'flyTo',
        rotateAnimation: false,
        callback: '',
        onChapterEnter: [],
        onChapterExit: [],
    }, {
        id: 'chapter_64',
        alignment: 'left',
        hidden: false,
        title: 'Mar 5: Railway Protests End',
        image: '',
        description: 'March 5 - The Listiguj First Nation also dismantle their rail blockades in Quebec.',
        location: {
            center: {
                lon: -66.73523,
                lat: 48.07067,
            },
            zoom: 9.69,
            pitch: 26.50,
            bearing: 0.00,
        },
        mapAnimation: 'flyTo',
        rotateAnimation: false,
        callback: '',
        onChapterEnter: [],
        onChapterExit: [],
    }, {
        id: 'chapter_65',
        alignment: 'left',
        hidden: false,
        title: 'Mar 7: Railway Services Restored',
        image: '',
        description: 'March 7 - Via Rail service has resumed on most routes, after disruption to more than 1,070 trips and roughly 165,000 passengers, according to Via Rail.Via Rail subsequently suspends The Canadian and Ocean services and reduces the frequency on the Winnipeg-Churchill route due to the COVID-19 pandemic, some time after the reinstatement announcement is made.',
        location: {
            center: [-94.93017, 57.67839],
            zoom: 3.48,
            pitch: 35.00,
            bearing: 0.59,
        },
        mapAnimation: 'flyTo',
        rotateAnimation: false,
        callback: '',
        onChapterEnter: [],
        onChapterExit: [],
    }, {
        id: 'chapter_66',
        alignment: 'left',
        hidden: false,
        title: 'Mar 10 - 21: Railway Services Restored',
        image: '',
        description: "March 10 - Speaking about the blockade on Highway 6 near Six Nations of the Grand River (begun February 24), Haldimand—Norfolk MPP Toby Barrett calls on anyone who can help to 'tear down this blockade', citing the fact that businesses in the area are suffering.\
	March 19 - The blockade on Highway 6 near Six Nations of the Grand River is removed after protesters and Six Nations chief Mark Hill come together and decide to leave the road and move back to Douglas Creek estates, known in the Mohawk language as Kanonhstaton 'the protected place',	a site which had been a focal point	for the long - standing Grand River land dispute.In a statement issued by the protesters, they say their departure is done 'as a sign of good faith'.\
	March 20 - The OPP West Region says they are working with the Ministry of Transportation of Ontario(MTO) to remove concrete barriers they hadset up around the protest.\
	March 21 - The OPP West Region tweets that Highway 6 is expected to re - open over the(March 21– 22) weekend.",
        location: {
            center: {
                lon: -79.92393,
                lat: 43.14717,
            },
            zoom: 9.60,
            pitch: 32.50,
            bearing: 0.00,
        },
        mapAnimation: 'flyTo',
        rotateAnimation: false,
        callback: '',
        onChapterEnter: [],
        onChapterExit: [],
    }, {
        id: 'chapter_67',
        alignment: 'left',
        hidden: false,
        title: 'Apr 30: Memorandum of Understanding Signed between Wet’ suwet’ en Hereditary Chiefs and Provincial and Federal Governments',
        image: '',
        description: "April 30 - The hereditary chiefs release a joint statement with the provincial and federal governments, stating that all five clans had agreed to ratify the MOU after having reviewed and discussed it in the prior weeks.\
		May 1 - The elected chiefs of five Wet’ suwet’ en band governments(Nee Tahi Buhn Indian Band, Skin Tyee Nation, Ts’ il Kaz Koh First Nation, Wet’ suwet’ en First Nation, and Witset First Nation) release their own joint statement, calling on the MOU to be withdrawn, saying they weren 't consulted properly. \
	May 7 - The MOU is released to the elected band councils.\
	May 8 - The MOU is released to the wider Wet’ suwet’ en Nation.\
	May 11 - The elected chiefs of Nee Tahi Buhn Indian Band, Skin Tyee Nation,	Ts’ il Kaz Koh First Nation, and Wet’ suwet’ en First Nation release a further statement, again calling on the MOU to be withdrawn,	and further calling	for the resignation of Minister Bennett.\
	May 12 - The MOU is published on the Office of the Wet’ suwet’ en website.\
	May 14 - The MOU is signed by the nine sitting hereditary chiefs, Minister Bennett,	and Minister Fraser, in a virtual ceremony held via Zoom due to precautions related to the COVID - 19 pandemic.",
        location: {
            center: [-123.38389, 53.64046],
            zoom: 5.35,
            pitch: 35.00,
            bearing: 0.59,
        },
        mapAnimation: 'flyTo',
        rotateAnimation: false,
        callback: '',
        onChapterEnter: [],
        onChapterExit: [],
    }, {
        id: 'chapter_68',
        alignment: 'left',
        hidden: false,
        title: 'Oct 1: Beginning of BC Supreum Court Hearing ',
        image: '',
        description: "October 1 - The B.C. Supreme Court hearing is scheduled to resume, with the Office of the Wet’suwet’en seeking a rejection of the province's decision to extend Coastal GasLink's environmental certificate for another five years. In their arguments, they cite the danger in establishing work camps on Indigenous territory, attested to in the Final report on Missing and murdered Indigenous women, which was published in June 2019 and not meaningfully considered when the decision was made. They also cite the company's four-year history of non-compliance with the Environmental Assessment Office's legally-binding conditions. They are desiring that additional conditions be imposed on the certificate as part of its extension. The Environmental Assessment Office's position is that it already has the power to impose further conditions outside of an extension, and that revoking the certificate would leave the project in a 'vacuum' since the last certificate expired in October 2019.",
        location: {
            center: [-123.38389, 53.64046],
            zoom: 5.35,
            pitch: 35.00,
            bearing: 0.59,
        },
        mapAnimation: 'flyTo',
        rotateAnimation: false,
        callback: '',
        onChapterEnter: [],
        onChapterExit: [],
    }],
};
